fix: getUserFromID from utility.js
bellshade/wpu_bot pull request #14
Opened 2022-01-09 16:42 UTC by dhafitf

Ada beberapa code yang saya ubah.
Dari kode yang direkomendasikan oleh @manh21 adalah seperti di bawah ini.
```js
let user = await getUserFromMention(args[0], client); // kode ini memberikan User
if (!user && args[0]) user = await msg.guild.members.fetch(args[0]); // kode ini memberikan GuildMember
if (!user) user = msg.author; // kode ini memberikan User
```
Kode di atas memberikan 2 property yang berbeda yaitu [User](https://discord.js.org/#/docs/main/stable/class/User) dan [GuildMember](https://discord.js.org/#/docs/main/stable/class/GuildMember).
Karena command `userinfo` memerlukan [GuildMember](https://discord.js.org/#/docs/main/stable/class/GuildMember), maka kodenya saya ubah menjadi seperti di bawah ini.
```js
let user = msg.mentions.users.first();
if (!user && args[0]) user = args[0];
if (!user) user = msg.author;
let member;
try {
    member = await msg.guild.members.fetch(user);
} catch (error) {
    console.log(error);
}
return member;
```

2022-01-09 17:08 UTC, manh21 commented on modules/utility.js
>          console.log(error);
Harusnya return false disini, sebaiknya penggunan try catch meliputi seluruh isi function untuk mengatasi hardcrash.

2022-01-09 17:12 UTC, manh21 commented on modules/utility.js
> +    const { args } = splitMessages(msg);
args seharusnya dikontrol oleh modules, kalo seperti ini tidak cocok di masukan ke dalam utility

2022-01-09 17:21 UTC, manh21 commented on modules/utility.js
> +    let user = msg.mentions.users.first();
recomendation
in module
`function (args[0], msg.guild)`

```js
function (msg, guild)
let user = getUserFromMention(msg, guild.client);
if(!user && msg) user = msg;
if(!user) user = msg.author;
const member = guild.members.fetch(user)
```
fetch bisa di isi dengan user atau id
https://discord.js.org/#/docs/discord.js/stable/class/GuildMemberManager?scrollTo=fetch

2022-01-10 15:51 UTC, dhafitf commented on modules/utility.js
> +    const { args } = splitMessages(msg);
oke fixed dengan cara memberikan parameter args lalu melemparkannya ke module

2022-01-10 18:16 UTC, manh21 commented on modules/info.js
> +        const { args } = splitMessages(msg);
Pemborosan function call, cukup di call 1 kali di line 12 
`const { command, args } = splitMessages`

2022-01-10 18:18 UTC, manh21 commented on modules/info.js
> +const Info = async (msg) => {
Tidak ada try catch akan menyebabkan hardcrash bot.

2022-01-10 18:19 UTC, manh21 commented on modules/info.js
>          if (Member === undefined) {
getUserFromMention akan return false atau user
rekomendasi
```js
if(Member){}
```

2022-01-10 18:20 UTC, manh21 commented on modules/info.js
> +        const role = await getRoleData(msg, args[0]);
await getRoleData kalau gagal akan return apa?

2022-01-10 18:21 UTC, manh21 commented on modules/info.js
>          if (role === undefined) {
Bagusnya menggunakan try catch yang mencakup seluruh function jadi tidak perlu check sepeti ini lagi

2022-01-10 18:23 UTC, manh21 commented on modules/info.js
> -        const customStatus =
```js
if(!member.presence && member.presence.activities && member.presence.activities[0]) {
     customStatus = member.presence.activities[0].state;
}
```
harusnya issues sudah teratasi dengan menggunakan lebih banyak check

2022-01-10 18:28 UTC, manh21 requested changes
Try Catch issues blocking this from merge

2022-01-11 12:27 UTC, dhafitf commented on modules/info.js
> -        const customStatus =
Oke, akan diperbaiki

2022-01-11 12:28 UTC, dhafitf commented on modules/info.js
> +        const role = await getRoleData(msg, args[0]);
Akan return `undefined`.

2022-01-11 15:50 UTC, manh21 commented on modules/info.js
>      function replyEmbedError(error) {
Kenapa buat function baru? di utlitily sudah ada function ini
https://github.com/bellshade/wpu_bot/blob/e9b2f096cc9e43ebcc1b4d4ece9ea3de3db67b42/modules/utility.js#L33-L38

2022-01-11 16:21 UTC, dhafitf commented on modules/info.js
>      function replyEmbedError(error) {
okay solved

2022-01-11 16:37 UTC, manh21 approved these changes
Looks good

2022-01-12 05:42 UTC, merged