add: wpu command
bellshade/wpu_bot pull request #73
Opened 2022-04-04 08:11 UTC by KimmyKx

2022-04-04 13:05 UTC, manh21 requested changes
.env.examples jangan di hapus

2022-04-04 13:23 UTC, KimmyKx commented
> .env.examples jangan di hapus

Ah iya pas mau balikin kena .gitignore `.env*` mesti ganti ke `.env` buat balikin itu gmn?

2022-04-04 13:47 UTC, manh21 commented
> Ah iya pas mau balikin kena .gitignore `.env*` mesti ganti ke `.env` buat balikin, itu gmn?

ilangin `*` di gitignore aja

2022-04-04 16:56 UTC, manh21 commented on modules/tag.js
> +        if(data[tag] && tag && checkSession(msg)) {
kenapa check session? kayaknya gak perlu di limit

2022-04-04 18:16 UTC, KimmyKx commented on modules/tag.js
> +        if(data[tag] && tag && checkSession(msg)) {
Oh takutnya ngespam sih, nanti ku ganti

2022-04-05 02:00 UTC, manh21 commented on modules/tag.js
> +require('dotenv').config();
ini dotenv udah gak di perluin di sini. di root file udah ada

2022-04-05 12:32 UTC, manh21 approved these changes
looks good

2022-04-05 12:32 UTC, merged